# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = TinyPlayer
DESTDIR = ../../bin
CONFIG += debug console
LIBS += -L"./../../lib" -l"F:/qt/5.15.2/msvc2019_64/lib/*"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(TinyPlayer.pri)
win32:RC_FILE = TinyPlayer.rc
